filter:
    excluded_paths:
        - 'Vendor/*'
checks:
    php:
        code_rating: true
        duplication: true

coding_style:
    php: {  }

tools:
    php_cs_fixer:
        config: { level: psr2 }
